
#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'dlh_salesforce'
version: '0.1.3'
config-version: 2

profile: 'snowflake_aicg'

require-dbt-version: ">=1.0.0"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"
# vars:    
#     source_database: DEVELOPER_SANDBOX
#     source_schema: DEMO_SALESFORCE
#     target_schema: SALESFORCE
    
models:
  dlh_salesforce:
