
#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'dlh_salesforce'
version: '0.1.0'
config-version: 2

profile: 'snowflake_aicg'


source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
target-path: "target"  
clean-targets: ["target", "dbt_packages"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

require-dbt-version: [">=0.21.0", "<2.0.0"]

vars:    
    dlh_salesforce:
        source_database: DEVELOPER_SANDBOX
        source_schema: DEMO_SALESFORCE
        target_schema: SALESFORCE

models:
  dlh_salesforce: