version: 2

sources:      
  - name: DEMO_SALESFORCE
    database: NISARG_DATABASE
    schema: NSLF_NISARG_SALESFORCE
    quoting:
      identifier: true
    tables:
      - name: LEAD
      - name: ACCOUNT
      - name: CONTACT
      - name: OPPORTUNITY
      - name: CAMPAIGN
      - name: CASE
      - name: ASSET
      - name: CONTRACT
      - name: USER
      - name: USERROLE
      - name: PROFILE