version: 2

sources:      
  - name: "{{ var('source_schema', 'DEMO_SALESFORCE')}}"
    database: "{{ var('source_database', 'DEVELOPER_SANDBOX')}}"
    schema: "{{ var('source_schema', 'DEMO_SALESFORCE')}}"
    quoting:
      identifier: true
    tables:
      - name: LEAD
      - name: ACCOUNT
      - name: CONTACT
      - name: OPPORTUNITY
      - name: CAMPAIGN
      - name: CASE
      - name: ASSET
      - name: CONTRACT
      - name: USER
      - name: USERROLE
      - name: PROFILE
      - name: PRODUCT2
      - name: PRICEBOOK2
      - name: PRICEBOOKENTRY
      