{{ config (
  materialized= 'view',
  schema= 'SALESFORCE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('DEMO_SALESFORCE','ACCOUNTS')}}
),

rename AS 
(
 SELECT
--DLHK
  MD5(ID) AS K_ACCOUNT_DLHK
  ,MD5( TRIM(COALESCE(JIGSAWCOMPANYID, '00000000000000000000000000000000'))  ) AS K_JIGSAW_COMPANY_DLHK
  ,MD5( TRIM(COALESCE(LASTMODIFIEDBYID, '00000000000000000000000000000000'))  ) AS K_LAST_MODIFIED_BY_USER_DLHK
  ,MD5( TRIM(COALESCE(OWNERID, '00000000000000000000000000000000'))  ) AS K_OWNER_USER_DLHK
  ,MD5( TRIM(COALESCE(PARENTID, '00000000000000000000000000000000'))  ) AS K_PARENT_DLHK
  ,MD5( TRIM(COALESCE(CREATEDBYID, '00000000000000000000000000000000'))  ) AS K_CREATED_BY_USER_DLHK
  ,MD5( TRIM(COALESCE(DANDBCOMPANYID,  '00000000000000000000000000000000'))  ) AS K_DAN_DB_COMPANY_DLHK
--BUSINESS KEYS
  .ID AS K_ACCOUNT_BK
  ,JIGSAWCOMPANYID AS K_JIGSAW_COMPANY_BK
  ,LASTMODIFIEDBYID AS K_LAST_MODIFIED_BY_USER_BK
  ,OWNERID AS K_OWNER_USER_BK
  ,PARENTID AS K_PARENT_BK
  ,CREATEDBYID AS K_CREATED_BY_USER_BK
  ,DANDBCOMPANYID AS K_DAN_DB_COMPANY_BK

  ,ACCOUNTNUMBER AS A_ACCOUNT_NUMBER
  ,ACCOUNTSOURCE AS A_ACCOUNT_SOURCE
  ,BILLINGCITY AS A_BILLING_CITY
  ,BILLINGCOUNTRY AS A_BILLING_COUNTRY
  ,BILLINGGEOCODEACCURACY AS A_BILLING_GEOCODE_ACCURACY
  ,BILLINGPOSTALCODE AS A_BILLING_POSTALCODE
  ,BILLINGSTATE AS A_BILLING_STATE
  ,BILLINGSTREET AS A_BILLING_STREET
  ,CLEANSTATUS AS A_CLEAN_STATUS
  ,CREATEDDATE AS A_CREATED_DATE
  ,DESCRIPTION AS A_DESCRIPTION
  ,DUNSNUMBER AS A_DUNSNUMBER
  ,FAX AS A_FAX
  ,INDUSTRY AS A_INDUSTRY
  ,JIGSAW AS A_JIGSAW
  ,LASTACTIVITYDATE AS A_LAST_ACTIVITY_DATE
  ,LASTMODIFIEDDATE AS A_LAST_MODIFIED_DATE
  ,LASTREFERENCEDDATE AS A_LAST_REFERENCED_DATE
  ,LASTVIEWEDDATE AS A_LAST_VIEWED_DATE
  ,NAICSCODE AS A_NAICS_CODE
  ,NAICSDESC AS A_NAICS_DESC
  ,NAME AS A_NAME
  ,NYN__ACTIVE__C AS A_NYN__ACTIVE__C
  ,NYN__CUSTOMERPRIORITY__C AS A_NYN__CUSTOMERPRIORITY__C
  ,NYN__SLAEXPIRATIONDATE__C AS A_NYN__SLAEXPIRATIONDATE__C
  ,NYN__SLASERIALNUMBER__C AS A_NYN__SLASERIALNUMBER__C
  ,NYN__SLA__C AS A_NYN__SLA__C
  ,NYN__UPSELLOPPORTUNITY__C AS A_NYN__UPSELLOPPORTUNITY__C
  ,OWNERSHIP AS A_OWNERSHIP
  ,PHONE AS A_PHONE
  ,PHOTOURL AS A_PHOTO_URL
  ,RATING AS A_RATING
  ,SHIPPINGCITY AS A_SHIPPING_CITY
  ,SHIPPINGCOUNTRY AS A_SHIPPING_COUNTRY
  ,SHIPPINGGEOCODEACCURACY AS A_SHIPPING_GEOCODE_ACCURACY
  ,SHIPPINGPOSTALCODE AS A_SHIPPING_POSTALCODE
  ,SHIPPINGSTATE AS A_SHIPPING_STATE
  ,SHIPPINGSTREET AS A_SHIPPING_STREET
  ,BILLINGLATITUDE AS A_BILLING_LATITUDE
  ,BILLINGLONGITUDE AS A_BILLING_LONGITUDE
  ,SHIPPINGLATITUDE AS A_SHIPPING_LATITUDE
  ,SHIPPINGLONGITUDE AS A_SHIPPING_LONGITUDE
  ,SIC AS A_SIC
  ,SICDESC AS A_SICDESC
  ,SITE AS A_SITE
  ,SYSTEMMODSTAMP AS A_SYSTEM_MODSTAMP
  ,TICKERSYMBOL AS A_TICKER_SYMBOL
  ,TRADESTYLE AS A_TRADE_STYLE
  ,TYPE AS A_TYPE
  ,WEBSITE AS A_WEBSITE
  ,YEARSTARTED AS A_YEAR_STARTED  
  ,ISDELETED AS B_IS_DELETED
  
  ,ANNUALREVENUE AS M_ANNUALREVENUE
  ,NUMBEROFEMPLOYEES AS M_NUMBEROFEMPLOYEES
  ,NYN__NUMBEROFLOCATIONS__C AS M_NYN__NUMBEROFLOCATIONS__C
    --METADATA
  ,CURRENT_TIMESTAMP as MD_LOAD_DTS
  ,'{{invocation_id}}' AS MD_INTGR_ID
FROM source 
)

SELECT * FROM rename