{{ config (
  materialized= 'view',
  schema= 'SALESFORCE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('DEMO_SALESFORCE','ACCOUNTS')}}
),

rename AS 
(
SELECT
    --DLHK
    MD5(ID) AS K_CONTACT_DLHK
    ,MD5( TRIM(COALESCE(ACCOUNTID, '00000000000000000000000000000000'))  ) AS K_ACCOUNT_DLHK
    ,MD5( TRIM(COALESCE(JIGSAWCONTACTID, '00000000000000000000000000000000'))  ) AS K_JIGSAW_CONTACT_DLHK
    ,MD5( TRIM(COALESCE(LASTMODIFIEDBYID, '00000000000000000000000000000000'))  ) AS K_LAST_MODIFIED_BY_USER_DLHK
    ,MD5( TRIM(COALESCE(OWNERID, '00000000000000000000000000000000'))  ) AS K_OWNER_USER_DLHK
    ,MD5( TRIM(COALESCE(REPORTSTOID, '00000000000000000000000000000000'))  ) AS K_REPORTS_TO_USER_DLHK
    ,MD5( TRIM(COALESCE(CREATEDBYID, '00000000000000000000000000000000'))  ) AS K_CREATED_BY_USER_DLHK
    ,MD5( TRIM(COALESCE(INDIVIDUALID, '00000000000000000000000000000000'))  ) AS K_INDIVIDUAL_DLHK
    --BUSINESS KEYS
    ,ID AS K_ID
    ,ACCOUNTID AS K_ACCOUNT_BK
    ,CREATEDBYID AS K_CREATED_BY_USER_BK    
    ,INDIVIDUALID AS K_INDIVIDUAL_BK
    ,JIGSAWCONTACTID AS K_JIGSAW_CONTACT_BK
    ,LASTMODIFIEDBYID AS K_LAST_MODIFIED_BY_USER_BK
    ,OWNERID AS K_OWNER_USER_BK
    ,REPORTSTOID AS K_REPORTS_TO_USER_BK
    --ATTRIBUTES
    ,ASSISTANTNAME AS A_ASSISTANT_NAME
    ,ASSISTANTPHONE AS A_ASSISTANT_PHONE
    ,BIRTHDATE AS A_BIRTH_DATE
    ,CLEANSTATUS AS A_CLEAN_STATUS
    ,CREATEDDATE AS A_CREATED_DATE
    ,DEPARTMENT AS A_DEPARTMENT
    ,DESCRIPTION AS A_DESCRIPTION
    ,EMAIL AS A_EMAIL
    ,EMAILBOUNCEDDATE AS A_EMAIL_BOUNCED_DATE
    ,EMAILBOUNCEDREASON AS A_EMAIL_BOUNCED_REASON
    ,FAX AS A_FAX
    ,FIRSTNAME AS A_FIRST_NAME
    ,HOMEPHONE AS A_HOME_PHONE
    ,JIGSAW AS A_JIGSAW
    ,LASTACTIVITYDATE AS A_LAST_ACTIVITY_DATE
    ,LASTCUREQUESTDATE AS A_LAST_CUREQUEST_DATE
    ,LASTCUUPDATEDATE AS A_LAST_CU_UPDATE_DATE
    ,LASTMODIFIEDDATE AS A_LAST_MODIFIED_DATE
    ,LASTNAME AS A_LAST_NAME
    ,LASTREFERENCEDDATE AS A_LAST_REFERENCED_DATE
    ,LASTVIEWEDDATE AS A_LAST_VIEWED_DATE
    ,LEADSOURCE AS A_LEAD_SOURCE
    ,MAILINGCITY AS A_MAILING_CITY
    ,MAILINGCOUNTRY AS A_MAILING_COUNTRY
    ,MAILINGGEOCODEACCURACY AS A_MAILING_GEOCODE_ACCURACY
    ,MAILINGPOSTALCODE AS A_MAILING_POSTALCODE
    ,MAILINGSTATE AS A_MAILING_STATE
    ,MAILINGSTREET AS A_MAILING_STREET
    ,MOBILEPHONE AS A_MOBILE_PHONE
    ,NAME AS A_NAME
    ,NYN__LANGUAGES__C AS A_NYN__LANGUAGES__C
    ,NYN__LEVEL__C AS A_NYN__LEVEL__C    
    ,OTHERCITY AS A_OTHER_CITY
    ,OTHERCOUNTRY AS A_OTHER_COUNTRY
    ,OTHERGEOCODEACCURACY AS A_OTHER_GEOCODE_ACCURACY
    ,OTHERPHONE AS A_OTHER_PHONE
    ,OTHERPOSTALCODE AS A_OTHER_POSTALCODE
    ,OTHERSTATE AS A_OTHER_STATE
    ,OTHERSTREET AS A_OTHER_STREET
    ,PHONE AS A_PHONE
    ,PHOTOURL AS A_PHOTOURL
    ,SALUTATION AS A_SALUTATION
    ,SYSTEMMODSTAMP AS A_SYSTEMMODSTAMP
    ,TITLE AS A_TITLE
    ,__ROW_MD5 AS A___ROW_MD5
    ,ISDELETED AS B_ISDELETED
    ,ISEMAILBOUNCED AS B_IS_EMAIL_BOUNCED
    ,MAILINGLATITUDE AS A_MAILING_LATITUDE
    ,MAILINGLONGITUDE AS A_MAILING_LONGITUDE
    ,OTHERLATITUDE AS A_OTHER_LATITUDE
    ,OTHERLONGITUDE AS A_OTHER_LONGITUDE
     --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID
FROM source 
)

SELECT * FROM rename